jobs:
  run-api-test:
    on: [pull_request, push]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.12.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2

      - name: Install poetry
        run: |
          pip install poetry
          poetry install --no-root

      - name: Run API test
        run: |
          poetry run pytest -v api/tests